services:
  mysql:
    image: mysql:8.0.32
    restart: always
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0782
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: 0782
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - spring-mysql

  spring-app:
    platform: linux/amd64
    container_name: my-spring-app
    image: kohyunchoel/pednav-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 0782
    networks:
      - spring-mysql

networks:
  spring-mysql:
      driver: bridge

volumes:
  mysql_volume:
    driver: local

